// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asoiytkmlzmcqeicmmfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzb2l5dGttbHptY3FlaWNtbWZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NDYzMjYsImV4cCI6MjA1OTUyMjMyNn0.GRX8Dt9rYHW8zqoUAAVSeWmu_VSczQfa97UZuLo9UuY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);